name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # Trigger the action only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # You can specify a Hugo version here

      - name: Install Node.js dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Build the Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # The default Hugo output directory
